services:
  backend:
    build: ./Backend
    container_name: logistics-backend
    # QUITAMOS 'ports' para que no sea accesible desde fuera
    expose:
      - "8080" # Solo visible para Nginx dentro de la red de Docker
    restart: unless-stopped

  frontend:
    image: nginx:alpine
    container_name: logistics-frontend
    ports:
      - "3000:80" # Único punto de entrada público
    volumes:
      - ./frontend/public:/usr/share/nginx/html:ro
      - ./frontend/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
